server:
  port: 8082

spring:
  mail:
    username: 2521220414@qq.com
    password: fttbhcmhqxhdebge
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  rabbitmq:
    username: "yeb"
    password: "yeb"
    virtual-host: "/yeb"
    host: 139.224.47.80
    port: 5672
  redis:
    #超时时间
    timeout: 5000ms
    #服务器地址
    #    host: 127.0.0.1
    host: 139.224.47.80
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #    #密码
    password: xjcredis
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5


